
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 21 20:28:02 CEST 2017
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int privee = 19;
  public static final int fintantque = 27;
  public static final int MULT = 4;
  public static final int idf = 35;
  public static final int pointvirgule = 17;
  public static final int operoper = 38;
  public static final int entier = 36;
  public static final int OU = 13;
  public static final int chaine = 37;
  public static final int debut = 15;
  public static final int INF = 9;
  public static final int si = 28;
  public static final int NON = 14;
  public static final int PAROUV = 6;
  public static final int DIV = 5;
  public static final int ecrire = 23;
  public static final int EGALEGAL = 10;
  public static final int PLUS = 2;
  public static final int classe = 20;
  public static final int EOF = 0;
  public static final int sinon = 30;
  public static final int alors = 29;
  public static final int error = 1;
  public static final int tantque = 25;
  public static final int fsi = 31;
  public static final int MOINS = 3;
  public static final int ET = 12;
  public static final int repeter = 26;
  public static final int PARFER = 7;
  public static final int CONSTANTEINT = 33;
  public static final int virgule = 22;
  public static final int CONSTANTEBOOL = 34;
  public static final int egal = 21;
  public static final int pour = 24;
  public static final int herite = 32;
  public static final int fin = 16;
  public static final int SUP = 8;
  public static final int publique = 18;
  public static final int DIFF = 11;
}

