
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 15 18:47:50 CET 2017
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int pointvirgule = 16;
  public static final int chaine = 27;
  public static final int OU = 13;
  public static final int PLUS = 2;
  public static final int ecrire = 22;
  public static final int SUP = 8;
  public static final int privee = 18;
  public static final int publique = 17;
  public static final int NON = 14;
  public static final int MOINS = 3;
  public static final int INF = 9;
  public static final int PARFER = 7;
  public static final int entier = 26;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int EGALEGAL = 10;
  public static final int DIV = 5;
  public static final int CONSTANTEBOOL = 24;
  public static final int ET = 12;
  public static final int error = 1;
  public static final int virgule = 21;
  public static final int egal = 20;
  public static final int classe = 19;
  public static final int PAROUV = 6;
  public static final int fin = 15;
  public static final int DIFF = 11;
  public static final int CONSTANTEINT = 23;
  public static final int idf = 25;
}

